### ISSUE TITLE
Replace assets/images/logo.png and favicon.ico

### ISSUE THREAD

**Issue by MartijnR** [odk-x/website#1]
Looks like logo.png is used for the OpenGraph meta data and possibly some facebook thing.

**Comment by MartijnR** [comment]
@maprehensive, just pinging you on this.

**Comment by maprehensive** [comment]
@MartijnR thanks, and sorry for the slow reply. 

TSC-2 is good with appending -X to the logo. Do you need me to change the logo, or is this just an FYI?

**Comment by MartijnR** [comment]
Great. Thanks! @adamvert has created a cool one for the new opendatakit.org landing page. I believe he'll be sharing this on the forum with tsc-2 shortly.

**Comment by maprehensive** [comment]
Thanks @MartijnR I'll keep an eye out for it.
