### ISSUE TITLE
Redesigning ODK-X Website

### ISSUE THREAD

**Issue by teelda** [odk-x/website#46]
**Objectives:**

The primary objectives is as follows:

- **Enhanced User Experience**: Improve the overall usability of the website to ensure that users can easily access important information and navigate the site without being redirected to the documentation or Github to view details like; values, code of conduct etc.

- **Modern Visual Design**: Update the website's design to be modern while adhering to utilitarianism. Ensure the design is accessible and inclusive by improving on the contrast, clear navigation and CTA's etc and it aligns to the ODK-X's design guidelines.

- **Streamlined Content**: Organize and streamline the current content for better readability and information accessibility for all users.

- **Mobile Responsiveness:** Ensure the website is fully responsive and accessible on various devices, including mobile phones and tablets.

**Comment by wbrunette** [comment]
@teelda we use the combined issue queue in the tool suite x project.
